In [15]:
import numpy as np
my_list1 = [1,2,3,4]
my_list2 = [11,22,33,44]
my_array = np.array(my_list1)
print("printing my_array",my_array)
my_lists = [my_list1, my_list2]
my_arrays = np.array(my_lists)
print("printing my arrays", my_arrays)
print("printing shape of 2 dim numpy array",my_arrays.shape)
print("data type of this array", my_arrays.dtype)
print("Array of zeroes", np.zeros(5))
print("Array of ones of required dimension", np.ones([5,5]))


print("Array of 5 numbers simple", np.arange(5))


print("Array of 5 to 50 at steps of 2", np.arange(5,50,2))

('printing my_array', array([1, 2, 3, 4]))
('printing my arrays', array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]]))
('printing shape of 2 dim numpy array', (2, 4))
('data type of this array', dtype('int64'))
('Array of zeroes', array([ 0.,  0.,  0.,  0.,  0.]))
('Array of ones of required dimension', array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]]))
('Array of 5 numbers simple', array([0, 1, 2, 3, 4]))
('Array of 5 to 50 at steps of 2', array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49]))


In [19]:
5.0/2, 5/2 #because its python 2

(2.5, 2)

In [20]:
from __future__ import division
5/2

2.5

In [22]:
arr1 = np.array([[1,2,3,4],[8,9,10,11]])
arr1*arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [23]:
arr1 - arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [24]:
1/arr1 # 1 divided by each element in the array

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.125     ,  0.11111111,  0.1       ,  0.09090909]])

In [25]:
arr1 ** 3 # exponential operation

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]])