In [19]:
import numpy as np
arr = np.arange(5)
arr
print('first version ',arr)
"""This saves the array arr to an array myarray. this has to be explicit in numpy. 
A regular variable assignment will only lead to modifying the existing array
array arr is now saved as myarray. myarray is actually an npy file to which the arr array was saved"""
np.save('myarray',arr) 
print('array saved now to file myarray.npy')
#myarray - this will not work as myarray is not an array. Its a file

arr = np.arange(10)
arr # now the original array is modified
print('original array modified ', arr)

np.load('myarray.npy')


('first version ', array([0, 1, 2, 3, 4]))
array saved now to file myarray.npy
('original array modified ', array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))


array([0, 1, 2, 3, 4])

In [23]:
arr1 = np.load('myarray.npy')
print(arr1)

arr2 = arr
print(arr2)

[0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]


In [25]:
np.savez('ziparray.npz',x=arr1,y=arr2) 
#savez creates a zip file of multiple arrays, the source arrays specified by positional parameters
np.load('ziparray.npz')

In [30]:
archive_array = np.load('ziparray.npz')
archive_array['x'] #first array seen from the zip


array([0, 1, 2, 3, 4])

In [31]:
archive_array['y'] #second array seen from the zip

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
np.savetxt('mytextarray.txt',arr,delimiter=',') 
#array saved in txt file with column values separated by a delimiter specified

In [40]:
arrz = np.loadtxt('mytextarray.txt', delimiter=',')
print(arrz) #loaded the file back into an array. by default now the numbers got loaded back as floating numbers as seen by .

[[ 1.  2.  3.]
 [ 4.  5.  6.]]
