In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1 = Series([0,1,2,],index=['T','U','V'])
ser2 = Series([3,4],index=['X','Y'])

In [7]:
ser1

X    3
Y    4
dtype: int64

In [8]:
ser2

X    3
Y    4
dtype: int64

In [9]:
#concatenate in pandas is concat and in numpy is concatenate
pd.concat([ser1,ser2],axis=0)

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1,ser2],axis=1)

0   1
T   0 NaN
U   1 NaN
V   2 NaN
X NaN   3
Y NaN   4

In [11]:
#Adding markers or keys to concat result
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [13]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])
dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [14]:
dframe1

X         Y         Z
0 -0.516238  0.759406  2.086882
1 -1.317199  0.486640 -0.913149
2  0.317004 -0.973532  0.142434
3  1.034940  1.045019 -0.827145

In [15]:
dframe2

Y         Q         X
0  0.781453  0.308506  0.357568
1  0.509190  1.418934  0.358305
2 -0.989611  0.358476 -1.560571

In [16]:
pd.concat([dframe1, dframe2]) #retained index info here 0 1 2 3 0 1 2 

Q         X         Y         Z
0       NaN -0.516238  0.759406  2.086882
1       NaN -1.317199  0.486640 -0.913149
2       NaN  0.317004 -0.973532  0.142434
3       NaN  1.034940  1.045019 -0.827145
0  0.308506  0.357568  0.781453       NaN
1  1.418934  0.358305  0.509190       NaN
2  0.358476 -1.560571 -0.989611       NaN

In [18]:
pd.concat([dframe1,dframe2],ignore_index=True) #ignored original index values

Q         X         Y         Z
0       NaN -0.516238  0.759406  2.086882
1       NaN -1.317199  0.486640 -0.913149
2       NaN  0.317004 -0.973532  0.142434
3       NaN  1.034940  1.045019 -0.827145
4  0.308506  0.357568  0.781453       NaN
5  1.418934  0.358305  0.509190       NaN
6  0.358476 -1.560571 -0.989611       NaN

In [19]:
url = 'http://pandas.pydata.org/pandas-docs/dev/generated/pandas.tools.merge.concat.html'

In [20]:
"""COMBINING DATAFRAMES WITH OVERLAPPING INDEXES"""

'COMBINING DATAFRAMES WITH OVERLAPPING INDEXES'

In [21]:
ser1 = Series([2,np.nan,4,np.nan,6,np.nan],
             index=['Q','R','S','T','U','V'])
ser1

Q     2
R   NaN
S     4
T   NaN
U     6
V   NaN
dtype: float64

In [23]:
ser2 = Series(np.arange(len(ser1)),dtype=np.float64,
             index=['Q','R','S','T','U','V'])
ser2

Q    0
R    1
S    2
T    3
U    4
V    5
dtype: float64

In [25]:
#Series where value of ser1 is chosen if corr value in ser2 is null
Series(np.where(pd.isnull(ser1), ser2, ser1),index = ser1.index)

Q    2
R    1
S    4
T    3
U    6
V    5
dtype: float64

In [26]:
Series(np.where(pd.isnull(ser1), ser2, ser1))

0    2
1    1
2    4
3    3
4    6
5    5
dtype: float64

In [27]:
ser1.combine_first(ser2) #combine ser1 with ser2, if ser1 has null value, use ser2 value

Q    2
R    1
S    4
T    3
U    6
V    5
dtype: float64

In [29]:
nan=np.nan
dframe_odds = DataFrame({'X':[1.,nan,3.,nan],
                        'Y':[nan,5.,nan,7.],
                        'Z':[nan,9.,nan,11.]})
dframe_odds

X   Y   Z
0   1 NaN NaN
1 NaN   5   9
2   3 NaN NaN
3 NaN   7  11

In [30]:
nan=np.nan
dframe_even = DataFrame({'X':[2.,4.,nan,6.,8.],
                        'Y':[nan,10.,12.,14.,16.]})
dframe_even

X   Y
0   2 NaN
1   4  10
2 NaN  12
3   6  14
4   8  16

In [32]:
dframe_odds.combine_first(dframe_even)

X   Y   Z
0  1 NaN NaN
1  4   5   9
2  3  12 NaN
3  6   7  11
4  8  16 NaN