In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [6]:
dframe = DataFrame(np.arange(16).reshape(4,4))
dframe

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [7]:
blender = np.random.permutation(4)
blender #creates any random permutation from within a series of 4

array([3, 2, 0, 1])

In [9]:
"""from dframe take rows from index 3, index 2, index 0 and index 1 in that order"""
dframe.take(blender)

0   1   2   3
3  12  13  14  15
2   8   9  10  11
0   0   1   2   3
1   4   5   6   7

In [28]:
box = np.array([4,10,14])

In [29]:
#randint method is permutation with replacement.
""" len(box) was passed as the max so all values stay <=3, and the size 10, so array of size 10"""
shaker = np.random.randint(0,len(box),size=10)
shaker

array([1, 2, 1, 0, 0, 2, 1, 2, 2, 2])

In [34]:
hand_grabs = box.take(shaker)
"""Each number in the random permutation given by shaker is treated as a location in the array box, and the 
number from there is selected to populate into the hand_grabs array"""
hand_grabs


array([10, 14, 10,  4,  4, 14, 10, 14, 14, 14])

In [35]:
shaker1 = np.random.randint(0,len(box),size=10)
shaker1

array([1, 0, 1, 2, 1, 2, 0, 2, 0, 1])

In [36]:
hand_grabs1 = box.take(shaker1)
hand_grabs1

array([10,  4, 10, 14, 10, 14,  4, 14,  4, 10])