In [1]:
import numpy as np
arr = np.arange(11)
print(arr)
print(np.sqrt(arr))


[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0.          1.          1.41421356  1.73205081  2.          2.23606798
  2.44948974  2.64575131  2.82842712  3.          3.16227766]


In [2]:
np.exp(arr) #exponential

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [4]:
A = np.random.randn(10) 
"""first calls random function from numpy library and then on the result, 
call the function randn which is a random normal distribution"""
A

array([ 2.23383997, -0.88188395, -0.18105798, -0.79407314,  0.80050158,
       -2.1096087 ,  2.09719189, -2.066511  ,  0.02671521, -1.18278426])

In [5]:
B = np.random.randn(10)
B

array([-0.56369379,  0.60307167,  0.18206758, -0.25298687,  0.08116534,
       -0.89706982,  0.08248906,  0.59991338,  1.34750239,  0.38433499])

In [7]:
# Binary Functions 
np.add(A,B) # adds corresponding elements of arrays

array([  1.67014618e+00,  -2.78812279e-01,   1.00960121e-03,
        -1.04706001e+00,   8.81666922e-01,  -3.00667851e+00,
         2.17968094e+00,  -1.46659762e+00,   1.37421760e+00,
        -7.98449268e-01])

In [10]:
np.maximum(A,B) #max of each corresponding value pair comparison

array([ 2.23383997,  0.60307167,  0.18206758, -0.25298687,  0.80050158,
       -0.89706982,  2.09719189,  0.59991338,  1.34750239,  0.38433499])

In [18]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available_ufuncs'

In [19]:
import webbrowser
webbrowser.open(website) #opens the url assigned to this website. this is the webbrowser package allowing us to do this

True